title: trbl dev blog
author: Terrible Developer
authorBio: > 
  I'm always 'reinventing the wheel', I love simplicity and minimalism, I hate using libraries and frameworks. 
  I have no former higher education and am self-taught in programming, english and pretty much everything else.
  
email: trbl@her.st
description: Self-Hosting, Minimalism, Linux, .NetCore. I'll take you on a programming adventure and before long, we will write terrible code together.
show_excerpts: true # set to true to show excerpts on the homepage
url: https://her.st/
paginate: 4
paginate_path: "/posts/:num/"
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

sass:
  style: compressed
dash:
  date_format: "%b %-d, %Y"
  social_links:
    - url: https://github.com/Alumniminium
      icon: https://cdn.her.st/assets/github.svg
    - url: /hosting/
      icon: https://cdn.her.st/assets/server.svg

pwa:
  sw_src_filepath: service-worker.min.js # Optional
  sw_dest_filename: service-worker.min.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,eot,svg,ttf,woff,webp,png,fonts}/**/*.{js,css,eot,svg,ttf,woff,webp,png,fonts}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.min.js
    - mainfest.json

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll/tagging
 - jekyll-pwa-plugin
 - jekyll-sitemap
 - jekyll-asciinema
 - jekyll-feed

collections:
  pages:
    output: true
    permalink: :slug/

twitter:
  card:             "summary_large_image"
